workflows:
  my-workflow:
    name: Firebase Distribution
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:

      groups:
        - firebase_credentials
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false

    scripts:
    # LATEST_BUILD_VERSION = $(firebase-app-distribution get-latest-build-version -p 448854262898 -a  1:448854262898:android:42f1a8984fc8549b13aeeb )
    #   - flutter build apk --release --build-number = $LATEST_BUILD_VERSION+1
        - flutter build apk --release
     

    artifacts:
      - build/**/outputs/**/*.apk
             
        # relative path for a project in root directory
    publishing:
      firebase:
      # use this line to authenticate via service account
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT

    # or this line to authenticate via token:
    # firebase_token: $FIREBASE_TOKEN

        android:
      # Add your Android app id retrieved from Firebase console
          app_id: 1:448854262898:android:42f1a8984fc8549b13aeeb 

      # Add one or more groups that you wish to distribute your Android application to.
      # You can create groups in the Firebase console
          # groups: 
          #   - androidTesters
          #   - ...

        ios:
        # Add your iOS app id retrieved from Firebase console
          app_id: 1:448854262898:ios:ac247841a6afd89a13aeeb

      # Add one or more groups that you wish to distribute your iOS application to.
      # You can create groups in the Firebase console
          # groups:
          #   - iosTesters
          #   - ...
      email:
        recipients:
          - bhattaraipoozan@gmail.com
      scripts:
        - echo 'Post-publish script'