name: whatsapp_stacked_architecture
description: A new Flutter project.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Firebase auth, crashlytics and Firestore database dependencies
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  firebase_messaging: ^14.6.8
  
  # Utils and other third party packages
  flutter_gen: ^5.3.2
  flutter_screenutil: ^5.9.0


  # Font dependencies of the app
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.1.0
  
  # Network dependencies of the app
  http: ^1.1.0

  # State management dependencies
  provider: ^6.0.5


  # Stacked architecture dependencies
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  mockito: ^5.4.2
  firebase_auth_mocks: ^0.12.0
  mock_exceptions: ^0.8.2
  fake_cloud_firestore: ^2.4.1+1
  firebase_remote_config: ^4.2.7
  firebase_analytics: ^10.5.1
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  stacked_generator: ^1.3.3


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets used in the app
  assets:
    - assets/images/
    - assets/icons/
   




